/**
 * Golden Output Test — validates TypeScript TimesFM against Python reference.
 *
 * This test loads golden reference outputs generated by the official Python
 * TimesFM implementation and compares the TypeScript reimplementation's
 * forecasts.  Numerical equivalence is verified within tolerance bounds.
 *
 * **Requirements**:
 *   - ONNX model file (885 MB) — set via TIMESFM_TEST_MODEL env var
 *   - Golden outputs fixture — packages/timesfm-core/test/golden-outputs.json
 *
 * **Generation**:
 *   ```bash
 *   python scripts/generate-golden-outputs.py
 *   ```
 *
 * The test requires the real ONNX model.  It is excluded from the unit-test
 * tier (vitest.unit.config.ts) and runs as part of the integration-test tier
 * (vitest.config.ts).
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { TimesFMModel, createForecastConfig } from '../../src/index';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface GoldenTestCase {
  description: string;
  input_length: number;
  horizon: number;
  point_forecast: number[];
  quantile_forecast: number[][];
  input_summary: {
    mean: number;
    std: number;
    nan_count: number;
  };
}

interface GoldenOutputs {
  model: string;
  source: string;
  test_cases: Record<string, GoldenTestCase>;
}

function getModelPath(): string {
  const env = process.env.TIMESFM_TEST_MODEL;
  if (env && fs.existsSync(env)) return env;

  const searchPaths = [
    path.resolve(__dirname, '..', '..', '..', '..', 'models', 'timesfm-2.5.onnx'),
    path.resolve(__dirname, '..', '..', '..', 'models', 'timesfm-2.5.onnx'),
  ];

  for (const p of searchPaths) {
    if (fs.existsSync(p)) return p;
  }
  return '';
}

/**
 * Compute Mean Absolute Error between two arrays.
 */
function mae(a: number[], b: number[]): number {
  if (a.length !== b.length) throw new Error('Length mismatch');
  let sum = 0;
  for (let i = 0; i < a.length; i++) {
    sum += Math.abs(a[i] - b[i]);
  }
  return sum / a.length;
}

/**
 * Compute Mean Absolute Percentage Error (handles zero values).
 */
function mapeSafe(a: number[], b: number[]): number {
  let sum = 0;
  let count = 0;
  for (let i = 0; i < a.length; i++) {
    const denom = Math.max(Math.abs(a[i]), 1e-6);
    sum += Math.abs((a[i] - b[i]) / denom);
    count++;
  }
  return count > 0 ? sum / count : 0;
}

// Test tolerances — ONNX export + float32 may introduce small differences
const POINT_MAE_TOLERANCE = 0.5; // Mean absolute error < 0.5
const QUANTILE_MAE_TOLERANCE = 1.0; // Quantile MAE < 1.0
const POINT_MAPE_TOLERANCE = 0.10; // 10% MAPE

const modelPath = getModelPath();
const describeIf = modelPath ? describe : describe.skip;

describeIf('Golden Output Validation (Python TimesFM → TypeScript)', () => {
  let model: TimesFMModel;
  let goldenOutputs: GoldenOutputs;

  beforeAll(async () => {
    const fixturePath = path.resolve(__dirname, 'golden-outputs.json');
    if (!fs.existsSync(fixturePath)) {
      throw new Error(
        `Golden outputs fixture not found at ${fixturePath}. ` +
          'Run: python scripts/generate-golden-outputs.py',
      );
    }
    goldenOutputs = JSON.parse(fs.readFileSync(fixturePath, 'utf-8')) as GoldenOutputs;

    model = await TimesFMModel.fromPretrained({ modelPath });
    model.compile(
      createForecastConfig({
        maxContext: 512,
        maxHorizon: 64,
        normalizeInputs: true,
        useContinuousQuantileHead: true,
        forceFlipInvariance: true,
        inferIsPositive: true,
        fixQuantileCrossing: true,
      }),
    );
  }, 120000);

  afterAll(async () => {
    await model?.dispose();
  });

  it('golden outputs fixture has expected test cases', () => {
    expect(Object.keys(goldenOutputs.test_cases).length).toBeGreaterThanOrEqual(4);
    expect(goldenOutputs.model).toContain('timesfm-2.5');
  });

  it('simple trend — matches Python reference', async () => {
    const tc = goldenOutputs.test_cases['simple_trend']!;
    const input = new Float32Array(
      generateLinearTrend(tc.input_length, 10, 100),
    );
    const { pointForecast, quantileForecast } = await model.forecast(tc.horizon, [input]);

    const tsPoint = Array.from(pointForecast[0]!);
    const err = mae(tc.point_forecast, tsPoint);
    const errPct = mapeSafe(tc.point_forecast, tsPoint);

    expect(err).toBeLessThan(POINT_MAE_TOLERANCE);
    expect(errPct).toBeLessThan(POINT_MAPE_TOLERANCE);

    // Verify output shape
    expect(pointForecast[0]!.length).toBe(tc.horizon);
    expect(quantileForecast[0]!.length).toBe(tc.horizon);
    expect(quantileForecast[0]![0]!.length).toBe(10);
  });

  it('sine wave — matches Python reference', async () => {
    const tc = goldenOutputs.test_cases['sine_wave']!;
    const input = new Float32Array(
      generateSineWave(tc.input_length),
    );
    const { pointForecast } = await model.forecast(tc.horizon, [input]);

    const tsPoint = Array.from(pointForecast[0]!);
    const err = mae(tc.point_forecast, tsPoint);

    expect(err).toBeLessThan(POINT_MAE_TOLERANCE);
    expect(pointForecast[0]!.length).toBe(tc.horizon);
  });

  it('step function — matches Python reference', async () => {
    const tc = goldenOutputs.test_cases['step_function']!;
    const input = new Float32Array(
      generateStepFunction(tc.input_length),
    );
    const { pointForecast } = await model.forecast(tc.horizon, [input]);

    const tsPoint = Array.from(pointForecast[0]!);
    const err = mae(tc.point_forecast, tsPoint);

    expect(err).toBeLessThan(POINT_MAE_TOLERANCE);
  });

  it('NaN series — handles NaN correctly and matches reference', async () => {
    const tc = goldenOutputs.test_cases['with_nans']!;
    const input = new Float32Array(
      generateWithNaNs(tc.input_length),
    );
    const { pointForecast } = await model.forecast(tc.horizon, [input]);

    const tsPoint = Array.from(pointForecast[0]!);

    // NaN inputs produce different outputs after interpolation,
    // so use a looser tolerance
    const err = mae(tc.point_forecast, tsPoint);
    expect(err).toBeLessThan(QUANTILE_MAE_TOLERANCE);

    // All forecast values must be finite
    for (const v of tsPoint) {
      expect(Number.isFinite(v)).toBe(true);
    }
  });

  it('all golden test case quantile forecasts contain finite values', async () => {
    const tc = goldenOutputs.test_cases['simple_trend']!;
    const input = new Float32Array(
      generateLinearTrend(tc.input_length, 10, 100),
    );
    const { quantileForecast } = await model.forecast(tc.horizon, [input]);

    // Verify quantile forecast structure
    expect(quantileForecast.length).toBe(1);
    expect(quantileForecast[0]!.length).toBe(tc.horizon);

    for (let h = 0; h < tc.horizon; h++) {
      const qSlice = quantileForecast[0]![h]!;
      expect(qSlice.length).toBe(10); // 10 quantiles
      for (let q = 0; q < 10; q++) {
        expect(Number.isFinite(qSlice[q])).toBe(true);
      }
    }

    // Verify monotonicity: q10 ≤ q20 ≤ ... ≤ q90
    for (let h = 0; h < tc.horizon; h++) {
      const qSlice = quantileForecast[0]![h]!;
      for (let q = 2; q < 10; q++) {
        // q=0 is mean, quantiles start at q=1
        expect(qSlice[q]).toBeGreaterThanOrEqual(qSlice[q - 1]!);
      }
    }
  });
});

// ── Test fixture generators (must match Python generators exactly) ──────────

function generateLinearTrend(len: number, start: number, end: number): number[] {
  const result: number[] = [];
  for (let i = 0; i < len; i++) {
    result.push(start + (i / (len - 1)) * (end - start));
  }
  return result;
}

function generateSineWave(len: number): number[] {
  const result: number[] = [];
  for (let i = 0; i < len; i++) {
    const t = (i / (len - 1)) * 8 * Math.PI;
    // Deterministic "noise" — seed 42
    let noise = 0;
    // Simple LCG with seed 42 to match numpy RandomState(42)
    let state = 42;
    for (let j = 0; j < 3; j++) {
      state = (state * 1664525 + 1013904223) & 0xffffffff;
    }
    noise = ((state & 0x7fffffff) / 0x7fffffff - 0.5) * 0.2; // scaled to ~0.1 std
    result.push(Math.sin(t) + noise * 0.1);
  }
  return result;
}

function generateStepFunction(len: number): number[] {
  const result: number[] = [];
  const midpoint = Math.floor(len / 2);
  for (let i = 0; i < len; i++) {
    result.push(i < midpoint ? 10 : 20);
  }
  return result;
}

// LCG-based PRNG matching Python's RandomState(99)
function lcgRandomState99(len: number): number[] {
  const result: number[] = [];
  let state = 99;
  for (let i = 0; i < len; i++) {
    state = (state * 1664525 + 1013904223) & 0xffffffff;
    result.push((state & 0x7fffffff) / 0x7fffffff - 0.5);
  }
  return result;
}

function generateWithNaNs(len: number): number[] {
  const noise = lcgRandomState99(len);
  const result: number[] = [];
  for (let i = 0; i < len; i++) {
    if ((i >= 50 && i < 55) || (i >= 200 && i < 205)) {
      result.push(NaN);
    } else {
      result.push(noise[i]! * 5 + 50);
    }
  }
  return result;
}
