/**
 * ModelDescriptor — the universal contract between ONNX models
 * and the TypeScript inference engine.
 *
 * Generated by `scripts/export-onnx.py` alongside the .onnx file.
 * The engine reads this at runtime to configure itself for any
 * compatible TimesFM model version, eliminating all hardcoded
 * architecture constants.
 *
 * @module model-descriptor
 */

import type { ModelConfig } from './types';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Schema version the current engine supports. */
export const ENGINE_SUPPORTED_SCHEMA = 1;

/** ONNX graph shape information extracted from the exported model. */
export interface OnnxDescriptor {
  readonly input_name: string;
  readonly input_shape: readonly number[];
  readonly outputs: Record<string, readonly number[]>;
  readonly opset: number;
  readonly sha256: string;
  readonly size_bytes: number;
}

/** TimesFM architecture parameters extracted from the PyTorch model. */
export interface ArchitectureDescriptor {
  readonly input_patch_len: number;
  readonly output_patch_len: number;
  readonly output_quantile_len: number;
  readonly num_layers: number;
  readonly num_heads: number;
  readonly model_dims: number;
  readonly quantiles: readonly number[];
  readonly context_limit: number;
}

/** Pre/post-processing strategy flags. */
export interface ProcessingDescriptor {
  readonly preprocessing: string;
  readonly postprocessing: readonly string[];
}

/** Model identity metadata. */
export interface ModelIdentity {
  readonly version: string;
  readonly variant: string;
  readonly hf_revision: string;
  readonly exported_at: string;
}

/**
 * Complete model descriptor — the JSON contract between
 * export-onnx.py and the TypeScript engine.
 */
export interface ModelDescriptor {
  readonly schema: number;
  readonly model: ModelIdentity;
  readonly onnx: OnnxDescriptor;
  readonly architecture: ArchitectureDescriptor;
  readonly processing: ProcessingDescriptor;
}

// ---------------------------------------------------------------------------
// Descriptor → ModelConfig conversion
// ---------------------------------------------------------------------------

/**
 * Convert a parsed ModelDescriptor into a ModelConfig for the engine.
 * This is the bridge between the self-describing model file and the
 * TypeScript inference pipeline.
 */
export function descriptorToModelConfig(desc: ModelDescriptor): ModelConfig {
  const arc = desc.architecture;
  const onx = desc.onnx;

  const quantiles = [...arc.quantiles] as readonly number[];
  const numQuantiles = quantiles.length + 1; // +1 for mean at index 0

  return Object.freeze({
    contextLimit: arc.context_limit,
    exportedPatches: onx.input_shape[1],
    inputPatchLen: arc.input_patch_len,
    outputPatchLen: arc.output_patch_len,
    outputQuantileLen: arc.output_quantile_len,
    outputPatchesPerInput: arc.output_patch_len / arc.input_patch_len,
    quantiles,
    decodeIndex: 5, // median position (quantiles are [0.1, 0.2, ..., 0.9], median=0.5 at index 5)
    numLayers: arc.num_layers,
    numHeads: arc.num_heads,
    modelDims: arc.model_dims,
    headDim: arc.model_dims / arc.num_heads,
    numQuantiles,
    tokenizerInputDims: arc.input_patch_len + arc.input_patch_len,
    tokenizerHiddenDims: arc.model_dims,
    tokenizerOutputDims: arc.model_dims,
    outputPointDims: arc.model_dims,
    outputQuantileDims: arc.output_quantile_len * numQuantiles,
  });
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

/**
 * Load and parse a model-descriptor.json file.
 *
 * @param path - Path to the directory containing model-descriptor.json
 *               (e.g., the same directory as the ONNX file).
 * @returns The parsed descriptor, or null if the file doesn't exist
 *          or is incompatible.
 */
export async function loadModelDescriptor(path: string): Promise<ModelDescriptor | null> {
  // Try multiple candidate filenames
  const candidates = [
    `${path}/model-descriptor.json`,
    path.replace(/\.onnx$/, '-descriptor.json'),
    path.replace(/\.onnx$/, '.onnx.meta.json'),
  ];

  for (const candidate of candidates) {
    try {
      const content = await readJsonFile(candidate);
      const desc = JSON.parse(content) as ModelDescriptor;
      return validateDescriptor(desc) ? desc : null;
    } catch {
      // File doesn't exist or can't parse — try next candidate
      continue;
    }
  }

  return null;
}

/**
 * Validate that a descriptor is compatible with the current engine.
 */
function validateDescriptor(desc: ModelDescriptor): boolean {
  if (!desc || typeof desc !== 'object') return false;
  if (typeof desc.schema !== 'number') return false;
  if (desc.schema > ENGINE_SUPPORTED_SCHEMA) {
    console.warn(
      `Model descriptor schema ${desc.schema} is newer than engine supports ` +
        `(${ENGINE_SUPPORTED_SCHEMA}). Please upgrade @agentix-e/timesfm-core.`,
    );
    return false;
  }
  if (!desc.architecture || !desc.onnx) return false;
  if (!desc.onnx.input_shape || desc.onnx.input_shape.length < 3) return false;
  return true;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Platform-agnostic file read. In Node.js, uses fs/promises.
 */
async function readJsonFile(filePath: string): Promise<string> {
  // Dynamic import to avoid bundling issues
  const { readFile } = await import('node:fs/promises');
  return readFile(filePath, 'utf-8');
}
